### ISSUE TITLE
Additional passes of pdflatex/bibtex needed

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1002]
The template files should be compiled with the following commands (only the first one is executed now):

```
pdflatex
bibtex
pdflatex
pdflatex
```

**Comment by brockho** [comment]
@dtusar: is this solved by now?

**Comment by brockho** [comment]
Could it be that #335 is caused by some new functionality of the tests which now actually do the bibtex run correctly?

**Comment by brockho** [comment]
I am closing this issue as #335 is now solved and because the pdfs show the bibliography correctly for me after the test is run.

**Comment by dtusar** [comment]
This still doesn't work on Mac. @nikohansen can you check on your Mac this:
In __main__.py uncomment the block of lines from 82 to 87 and run `python do.py test-postprocessing`.

You should get an error like this: Test failed: error while running bibtex on templateBBOBarticle. On the other slaves this test goes through. I saw that on the linux slave we have a different bibtex version (0.99c vs. Mac's 0.99d) but I'm not sure if this is the reason. Do you have any idea?

**Comment by nikohansen** [comment]
After some research I figure that you probably mean `code-postprocessing/bbob_pproc/__main__.py`? 

```
[08:00:20] 0 coco$ python do.py test-postprocessing
EXPAND	code-postprocessing/setup.py.in to code-postprocessing/setup.py
PYTHON	setup.py install --user in code-postprocessing
PYTHON	__main__.py in code-postprocessing/bbob_pproc
ERROR: return value=1

Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Using grayscale settings.

Post-processing (1): will generate output data in folder ppdata/BFGS_ros_noiseless
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
Generating convergence plots...
  done (Mon Aug  8 08:02:18 2016).
Scaling figures...
  Loading best algorithm data from bestalgentries2009.pickle.gz ...
  done (Mon Aug  8 08:02:37 2016).
Generating LaTeX tables...
  done (Mon Aug  8 08:02:37 2016).
ECDF graphs...
  done (Mon Aug  8 08:02:48 2016).
ECDF graphs per function...
  done (Mon Aug  8 08:03:54 2016).
aRT loss ratio figures and tables...
  done (Mon Aug  8 08:03:58 2016).
Output data written to folder ppdata/BFGS_ros_noiseless
  done (Mon Aug  8 08:03:58 2016).
WARNING: this tests the post-processing, this might change in future (use -h for help)
preparing algorithm data
LaTeX templates copied.
*** testing module bbob_pproc ***
python -m  bbob_pproc --no-svg --settings=grayscale --conv /Users/hansen/git/coco/code-postprocessing/bbob_pproc/data/BFGS_ros_noiseless.tgz
('**  subtest 1 finished in ', 125.13935708999634, ' seconds')
Traceback (most recent call last):
  File "__main__.py", line 331, in <module>
    main(args)
  File "__main__.py", line 195, in main
    run_latex_template("templateBBOBarticle.tex")
  File "__main__.py", line 87, in run_latex_template
    assert not result, 'Test failed: error while running bibtex on %s.' % os.path.splitext(filename)[0]
AssertionError: Test failed: error while running bibtex on templateBBOBarticle.

Traceback (most recent call last):
  File "do.py", line 857, in <module>
    main(sys.argv[1:])
  File "do.py", line 846, in main
    elif cmd == 'test-postprocessing': test_postprocessing()
  File "do.py", line 641, in test_postprocessing
    python('code-postprocessing/bbob_pproc', ['__main__.py'], verbose=verbosity)
  File "/Users/hansen/git/coco/code-experiments/tools/cocoutils.py", line 144, in python
    universal_newlines=True)
  File "/Users/hansen/git/coco/code-experiments/tools/cocoutils.py", line 42, in check_output_with_print
    output = check_output(*popenargs, **kwargs)
  File "/Users/hansen/anaconda2/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/Users/hansen/anaconda2/bin/python', '__main__.py']' returned non-zero exit status 1
[08:03:59] 0 coco$ 
```

**Comment by dtusar** [comment]
> After some research I figure that you probably mean code-postprocessing/bbob_pproc/__main__.py? 

Yes, this one. You can check in the `bibtex.log` file (in the same folder) why the bibtex fails. On the mac slave the log file contains the error "couldn't open file .../templateBBOBArticle.blg'". But the file is there and I can open it manually so I'm not sure what is the problem.

**Comment by nikohansen** [comment]
same message `I couldn't open file name 
'/.../code-postprocessing/bbob_pproc/templateBBOBarticle.blg'`, 
however the file is not there (and also nowhere in the repository folders or subfolders), so the message seems justified.

**Comment by NDManh** [comment]
Hi @nikohansen, the issue is probably due to the path of command `pdflatex`. I have encoutered the same problem after updating Mac El Capital to version 10.11.6 (15G31), and just fixed it. Here are some information which is maybe useful for you.
1) Before updating Mac (I used MacTex 2015) I didn't see this issue, so I am sorry I don't know where is the path of this command `pdflatex`.

2) After updating Mac, the path of command `pdflatex` is:
```
pc30:~ NGUYEN$ which pdflatex
/opt/local/bin/pdflatex
```
which is quite different from the information described in the documentation `http://tug.org/mactex/UpdatingForElCapitan.pdf`. I cannot run the command `python do.py test-postprocessing` anymore. Moreover I went to the folder `code-postprocessing/bbob_pproc` and tried the command `pdflatex templateBBOBarticle.tex`, then it required the `xkeyval` package. After providing this package, it continuously asked the others which I do not remember.

3) Finally, I decided to re-install MacTex 2016. Also, I have tracked this path and found that:
```
pc30:coco NGUYEN$ which pdflatex
/Library/TeX/texbin/pdflatex
```
Now, the command `python do.py test-postprocessing` is back to normal.

**Comment by brockho** [comment]
Many thanks @NDManh. If this solves the bug consistently (i.e. for example also for @nikohansen), we should add this issue to the list of known issues in our https://github.com/numbbo/coco/blob/master/README.md file.

**Comment by nikohansen** [comment]
this is neither a bug I reported nor am I affected by it. I only did a test of a modification as asked for by @dtusar to diagnose, I believe, a problem in a CI machine. On the other hand, I also believe to remember that after installation of El Capitan I reinstalled Latex, probably for a reason.

**Comment by nikohansen** [comment]
however, calling the module for testing fails again (I believe it was working before):
```
[08:16:56] 0 ~$ python -m bbob_pproc --test
preparing algorithm data
LaTeX templates copied.
*** testing module bbob_pproc ***
python -m  bbob_pproc --no-svg --settings=grayscale --conv /Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3.175-py2.7.egg/bbob_pproc/data/BFGS_ros_noiseless.tgz

Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Using grayscale settings.

Post-processing (1): will generate output data in folder ppdata/BFGS_ros_noiseless
  this might take several minutes.
    archive extracted to folder /Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3.175-py2.7.egg/bbob_pproc/data/_extracted_BFGS_ros_noiseless ...
  Data consistent according to test in consistency_check() in pproc.DataSet
Generating convergence plots...
  done (Sun Aug 14 08:21:08 2016).
Scaling figures...
  Loading best algorithm data from bestalgentries2009.pickle.gz ...
  done (Sun Aug 14 08:21:29 2016).
Generating LaTeX tables...
  done (Sun Aug 14 08:21:29 2016).
ECDF graphs...
  done (Sun Aug 14 08:21:41 2016).
ECDF graphs per function...
  done (Sun Aug 14 08:23:08 2016).
aRT loss ratio figures and tables...
  done (Sun Aug 14 08:23:13 2016).
Output data written to folder ppdata/BFGS_ros_noiseless
  done (Sun Aug 14 08:23:13 2016).
('**  subtest 1 finished in ', 154.87761187553406, ' seconds')
Traceback (most recent call last):
  File "/Users/hansen/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/hansen/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3.175-py2.7.egg/bbob_pproc/__main__.py", line 334, in <module>
    main(args)  # is not likely to work
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3.175-py2.7.egg/bbob_pproc/__main__.py", line 195, in main
    run_latex_template("templateBBOBarticle.tex")
  File "/Users/hansen/.local/lib/python2.7/site-packages/bbob_pproc-1.1.3.175-py2.7.egg/bbob_pproc/__main__.py", line 80, in run_latex_template
    assert not result, 'Test failed: error while generating pdf from %s.' % filename
AssertionError: Test failed: error while generating pdf from templateBBOBarticle.tex.
```

**Comment by NDManh** [comment]
On my Mac: the above command 
```
pc30:coco NGUYEN$ python -m bbob_pproc --test
``` 
also fails as you reported but the command `python do.py test-postprocessing` is ok.

**Comment by brockho** [comment]
I can add that also on my Windows machine, `python -m bbob_pproc --test` does not work. The reason is that the `ppdata` folder is created in the folder where you run the test while the LaTeX templates lie typically somewhere else. Together with @nikohansen, we therefore agreed yesterday, to close the issue for now and have the standard procedure for running the test go through the `do.py` (which is working consistently) while the `--test` shall become simply unsupported (it is not documented anyway at the moment, I guess).

**Comment by brockho** [comment]
@dtusar: would you be so kind and check whether (re-)installing LaTeX on the Mac slave solves the problem now? Unfortunately, I cannot connect to Jenkins right now from here (don't know why and hope that it is just related to my current location and that it works again when I am in Europe).

**Comment by dtusar** [comment]
I reinstalled LaTeX on the Mac slave and it didn't solve the problem.

**Comment by NDManh** [comment]
Hi @dtusar, I think that the path of command `pdflatex` should be `/Library/TeX/texbin/pdflatex` if MacTex2015+ is installed. Can you check it?`

**Comment by dtusar** [comment]
The `pdflatex` call works, we get an error when calling `bibtex`.

**Comment by NDManh** [comment]
It seems that `bibtex` can not work outside the folder `code-postprocessing/bbob_pproc` because after after successful with `pdflatex` and fails with `bibtex`
1) If go to the folder `code-postprocessing/bbob_pproc`:
```
pc5-174:bbob_pproc NGUYEN$ bibtex templateBBOBarticle
This is BibTeX, Version 0.99d (TeX Live 2016)
The top-level auxiliary file: templateBBOBarticle.aux
The style file: abbrv.bst
Database file #1: bbob.bib
pc5-174:bbob_pproc NGUYEN$ 
```
`bibtex` works perfectly.

2) If I stay at the folder `coco`:
```
pc5-174:coco NGUYEN$ bibtex code-postprocessing/bbob_pproc/templateBBOBarticle
This is BibTeX, Version 0.99d (TeX Live 2016)
The top-level auxiliary file: code-postprocessing/bbob_pproc/templateBBOBarticle.aux
The style file: abbrv.bst
I couldn't open database file bbob.bib
---line 9 of file code-postprocessing/bbob_pproc/templateBBOBarticle.aux
 : \bibdata{bbob
 :              }
I'm skipping whatever remains of this command
I found no database files---while reading file code-postprocessing/bbob_pproc/templateBBOBarticle.aux
Warning--I didn't find a database entry for "hansen2009fun"
Warning--I didn't find a database entry for "hansen2016exp"
Warning--I didn't find a database entry for "hansen2016perfass"
Warning--I didn't find a database entry for "wp200901_2010"
Warning--I didn't find a database entry for "hansen2012fun"
Warning--I didn't find a database entry for "hansen2016cocoplat"
(There were 2 error messages)
```

**Comment by NDManh** [comment]
I am sorry for making a confusion, the command `python do.py test-postprocessing`, which I talk above, run successfully only with `pdflatex`, not `bibtex`. Before, I have problem `pdflatex` (and solved) rather than `bibtex`.

**Comment by brockho** [comment]
Just as a try, I added `./` to the LaTeX templates. Can someone check whether this improves on the issue? Otherwise, I'll take it out again from the development branch.

**Comment by dtusar** [comment]
The problem here is that this only fails on mac and it works on all other slaves. I noticed that on Linux the bibtex version is 0.99c and on Mac the bibtex version is 0.99d. I don't know if this is relevant but on two Windows slaves I had a similar problem. 

On one of them the bibtex from cygwin was called and it didn't work. Then I changed the order in the PATH environment variable so that the bibtex from MikTeX is called and it went through. 

So I would like to try with the bibtex 0.99c also on mac but I don't know how to downgrade it.

**Comment by NDManh** [comment]
Hi @brockho, adding `./`  to the LaTeX templates does not solve the issue on my Mac.

**Comment by NDManh** [comment]
Hi, it's probably not a good solution, but  it works well at least on my Mac and Windows machines, that is we replace the line code `filePath = os.path.splitext(filePath)[0]` (line 82 in the file `code-postprocessing/bbob_pproc/__main__.py`) by the following `filePath = os.path.splitext(filename)[0]`.

**Comment by nikohansen** [comment]
Was the error `bbob.bib` not found?

**Comment by NDManh** [comment]
There is no error on my machines. This file `bbob.bib` resides in the folder `code-postprocessing/bbob_pproc` when running `python do.py test-postprocessing`. And I think that it is copied from the folder `coco/code-postprocessing/latex-templates`, right?

**Comment by brockho** [comment]
In a joint effort with @asmaatamna, @ttusar, and @dtusar, we finally found a way to make bibtex run also on the Mac via `python do.py test-postprocessing`. The issue actually contained two problems:

1) Under Mac, `bibtex` seems to be messed up a bit with respect to absolute and relative paths. In order to fix this, `openout_any = a` should be added to the `texmf.cnf` file in the local TeX path (type `kpsewhich texmf.cnf` to find out where this actually is). Note that since `python do.py test-postprocessing` is not run by the user typically, this does not need to be done by everybody.

2) The `ACM-Reference-Format.bst` file of the GECCO ACM style was not included in the TeXLive distribution.

While the first item is fixed now on the Mac Slave of our CI, the second item will be fixed soon by adding the file to the repo. As soon as this is done and the test runs through, the issue can be eventually closed.
